apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sqlcredentials.sql.kodebrew.com
spec:
  group: sql.kodebrew.com
  names:
    kind: SQLCredential
    listKind: SQLCredentialList
    plural: sqlcredentials
    singular: sqlcredential
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
